[workspace]
resolver = "2"
members = [
    "sys",
    "field",
    "base",
    "protocol",
    "vm",
    "mint",
    "chain",
    "node",
    "server",
    "api",
    "app",
    "sdk",
    "db",
    "x16rs",
]

default-members = [
    "sys",
    "field",
    "base",
    "protocol",
    "vm",
    "mint",
    "chain",
    "node",
    "server",
    "api",
    "app",
    "sdk",
    "db",
    "x16rs",
]

[workspace.package]
version = "1.0.0"
edition = "2024"

[workspace.dependencies]
sys        = { path = "sys" }
field      = { path = "field" }
base       = { path = "base" }
protocol   = { path = "protocol" }
vm         = { path = "vm" }
mint       = { path = "mint" }
chain      = { path = "chain" }
node       = { path = "node" }
server     = { path = "server" }
api        = { path = "api" }
app        = { path = "app" }
sdk        = { path = "sdk" }
db         = { path = "db", default-features = false }
x16rs      = { path = "x16rs" }

[profile.release]
debug = false
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true

[profile.wasm-release]
inherits = "release"
opt-level = "z"
