[package]
name = "hacash"
version = "0.2.0"
edition = "2021"

[dependencies]
x16rs = {path = "./x16rs"}
sys = {path = "./sys"}
field = {path = "./field"}
vm = {path = "./vm"}
protocol = {path = "./protocol"}
chain = {path = "./chain"}
mint = {path = "./mint"}
node = {path = "./node"}
server = {path = "./server"}
ctrlc = "3.4.5"



