[package]
name = "sys"
version.workspace = true
edition.workspace = true

[dependencies]
sha3 = "0.10"
sha2 = "0.10"
ripemd = "0.1"
base58check = "0.1"
libsecp256k1 = { version = "0.7.2", features = ["hmac", "static-context"], default-features = false }
base64 = "0.22"
hex = "0.4"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
serde = { version = "1", features = ["derive"] }
