[package]
name = "protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
x16rs = {path = "../x16rs"}
sys = {path = "../sys"}
field = {path = "../field"}
vm = {path = "../vm"}
dyn-clone = "1.0.17"
concat-idents = "1.1.5"
