[package]
name = "mint"
version.workspace = true
edition.workspace = true

[dependencies]
sys = { workspace = true, features = ["secp-static-context"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
field = { workspace = true, features = ["json-serde", "num-bigint"] }
base = { workspace = true }
protocol = { workspace = true }
x16rs = { workspace = true }
mint-core = { workspace = true, features = ["execute"] }
num-bigint = "0.4"
num-traits = "0.2"
hex = "0.4"
ocl = { version = "0.19.7", optional = true }

[features]
ocl = ["dep:ocl"]
