

[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "target-feature=+crt-static"]


[target.x86_64-apple-darwin]
rustflags = ["-C", "target-feature=+crt-static"]
# linker = "x86_64-apple-darwin14-clang"
# ar = "x86_64-apple-darwin14-ar"


[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]


[target.x86_64-pc-windows-gnu]
rustflags = ["-C", "target-feature=+crt-static"]
# linker = "x86_64-w64-mingw32-gcc"
# ar = "x86_64-w64-mingw32-gcc-ar"



