//! SDK code generation — friendly `ActionSpec` adapter + operation/error tables.
//!
//! `sdk_codegen` (src/bin/sdk_codegen.rs) renders `sdk/js/generated/`
//! artifacts from the Rust single sources (`actionspec::ACTION_SPECS`,
//! `profile::OPERATIONS`, `error::ERROR_CODES`). The checked-in copies are
//! verified by the `generated_artifacts_match` test below, so editing a
//! generated file or adding an action without regenerating fails CI.

use crate::actionspec::{FieldDef, FriendlyGroup, JsConv, JsSubConv, RustConv, ACTION_SPECS, friendly_groups};
use crate::profile::{OpDef, OpRequestField};

fn js_quote(s: &str) -> String {
    format!("{s:?}")
}

// ================================ op/error tables ================================

/// `op_tables.mjs`: operation ids and error names (Rust `OPERATIONS` +
/// `ERROR_CODES`; the JS facade imports these instead of duplicating them).
pub fn render_op_tables() -> String {
    let mut out = String::new();
    out.push_str("// GENERATED by `sdk_codegen` (cargo run -p sdk --bin sdk_codegen). DO NOT EDIT.\n");
    out.push_str("// Single source: Rust `profile::OPERATIONS` and `error::ERROR_CODES`.\n\n");
    out.push_str("export const OP = {\n");
    for (i, name) in crate::profile::OPERATIONS.iter().enumerate() {
        let key = name.to_uppercase().replace('.', "_");
        out.push_str(&format!("    {key}: {},\n", i + 1));
    }
    out.push_str("};\n\n");
    out.push_str("export const ERROR_NAMES = [\n    null,\n");
    for code in crate::error::ERROR_CODES {
        out.push_str(&format!("    {},\n", js_quote(code)));
    }
    out.push_str("];\n");
    out
}

// ================================ operation methods ================================

/// `operations.mjs`: the JS facade operation methods, derived from
/// `profile::OP_DEFS` (group, method and binary request layout). `special`
/// operations keep hand-written bodies in `hacashsdk.mjs`.
pub fn render_operations_mjs() -> String {
    use crate::profile::{OP_DEFS, OpDef};
    let mut out = String::new();
    out.push_str("// GENERATED by `sdk_codegen` (cargo run -p sdk --bin sdk_codegen). DO NOT EDIT.\n");
    out.push_str("// Single source: Rust `sdk::profile::OP_DEFS` — the binary request layout per\n");
    out.push_str("// operation (parsed by `service::parse_request` from the same table). `special`\n");
    out.push_str("// operations (tx.build) keep hand-written bodies in `hacashsdk.mjs`.\n\n");
    out.push_str("import { OP } from \"./op_tables.mjs\";\n\n");
    out.push_str("export function createOperationMethods(invoke, push) {\n");
    out.push_str("  const { pushW2Str, pushOptW2Str, pushW4Json, pushOptW4Json, pushOptU64, pushOptInspectContext } = push;\n");
    out.push_str("  return {\n");

    let mut groups: Vec<(&'static str, Vec<&'static OpDef>)> = Vec::new();
    for def in OP_DEFS {
        if let Some((_, list)) = groups.iter_mut().find(|(g, _)| *g == def.group) {
            list.push(def);
        } else {
            groups.push((def.group, vec![def]));
        }
    }
    for (group, defs) in groups {
        out.push_str(&format!("    {group}: {{\n"));
        for def in defs {
            if def.special {
                out.push_str(&format!(
                    "      // {}: special, body is hand-written in hacashsdk.mjs\n",
                    def.method
                ));
                continue;
            }
            out.push_str(&format!("      {}: ({}) => {{\n", def.method, op_params(def)));
            out.push_str("        const out = [];\n");
            for field in def.request {
                out.push_str(&format!("        {}\n", op_field_stmt(field)));
            }
            let op_const = format!("{}.{}", group, def.method).to_uppercase().replace('.', "_");
            out.push_str(&format!("        return invoke(OP.{op_const}, out);\n"));
            out.push_str("      },\n");
        }
        out.push_str("    },\n");
    }
    out.push_str("  };\n");
    out.push_str("}\n");
    out
}

/// Distinct argument roots in request order (dotted names contribute their
/// root, e.g. `options.review` → `options`).
fn op_params(def: &OpDef) -> String {
    use crate::profile::OpRequestField;
    let mut params: Vec<&str> = Vec::new();
    for field in def.request {
        let arg = field.arg_name();
        let root = arg.split('.').next().expect("non-empty arg");
        if !params.contains(&root) {
            params.push(root);
        }
    }
    params.join(", ")
}

/// One request-field statement. Dotted names read from the trailing options
/// object (`options?.x ?? null`); plain names are positional parameters.
fn op_field_stmt(field: &OpRequestField) -> String {
    use crate::profile::OpRequestField;
    match field {
        OpRequestField::W2Str(a) => format!("pushW2Str(out, {a});"),
        OpRequestField::OptW2Str(a) => format!("pushOptW2Str(out, {});", opt_expr(a)),
        OpRequestField::W4Json(a) => format!("pushW4Json(out, {a});"),
        OpRequestField::OptW4Json(a) => format!("pushOptW4Json(out, {});", opt_expr(a)),
        OpRequestField::OptU64(a) => format!("pushOptU64(out, {});", opt_expr(a)),
        OpRequestField::U8(a) => format!("out.push(Number({a}) & 0xff);"),
        OpRequestField::OptInspectContext(a) => {
            format!("pushOptInspectContext(out, {a});")
        }
    }
}

fn opt_expr(arg: &str) -> String {
    match arg.split_once('.') {
        Some((root, rest)) => format!("{root}?.{rest} ?? null"),
        None => arg.to_owned(),
    }
}

// ================================ action spec adapter ================================

/// `actionspec.mjs`: the friendly `ActionSpec` → wire action adapter, derived
/// from `ACTION_SPECS` (field conversions and kind selection are table data).
pub fn render_actionspec_mjs() -> String {
    let mut out = String::new();
    out.push_str("// GENERATED by `sdk_codegen` (cargo run -p sdk --bin sdk_codegen). DO NOT EDIT.\n");
    out.push_str("// Single source: Rust `sdk::actionspec::ACTION_SPECS`.\n\n");
    out.push_str("function toHex(text) {\n");
    out.push_str("    return Array.from(new TextEncoder().encode(text))\n");
    out.push_str("        .map((b) => b.toString(16).padStart(2, \"0\"))\n");
    out.push_str("        .join(\"\");\n");
    out.push_str("}\n\n");
    out.push_str("function toHexOrKeep(text) {\n");
    out.push_str("    if (text.startsWith(\"0x\") || text.startsWith(\"0X\")) {\n");
    out.push_str("        return text.slice(2);\n");
    out.push_str("    }\n");
    out.push_str("    return toHex(text);\n");
    out.push_str("}\n\n");
    out.push_str("export function adaptActionSpec(action) {\n");
    out.push_str("    const a = { ...action };\n");
    out.push_str("    switch (a.kind) {\n");
    for group in friendly_groups() {
        render_js_case(&mut out, &group);
    }
    out.push_str("    }\n");
    out.push_str("    return a;\n");
    out.push_str("}\n");
    out
}

fn render_js_case(out: &mut String, g: &FriendlyGroup) {
    out.push_str(&format!("        case {}: {{\n", js_quote(g.friendly)));
    if let Some(single) = g.single_entry {
        // names-flow: single / list / from_to, derived from the single+list entries
        let (names_field, single_wire) = single
            .fields
            .iter()
            .find_map(|f| match f.js {
                JsConv::HexSingle(w) => Some((f.friendly, w)),
                _ => None,
            })
            .expect("single entry has HexSingle");
        let list_wire = g
            .list_entry
            .and_then(|d| {
                d.fields.iter().find_map(|f| match f.js {
                    JsConv::HexList(w) => Some(w),
                    _ => None,
                })
            })
            .expect("list entry has HexList");
        let names = names_field;
        let from_to = g.from_to_kind.expect("from_to kind");
        let to = g.list_entry.expect("list entry").kind;
        out.push_str(&format!(
            "            const {names} = (a.{names} ?? []).map(toHex);\n",
            names = names
        ));
        out.push_str("            if (a.from) {\n");
        out.push_str(&format!(
            "                a.kind = {}; a.{list_wire} = {names};\n",
            js_quote(from_to),
            list_wire = list_wire,
            names = names
        ));
        out.push_str(&format!(
            "            }} else if ({names}.length === 1) {{\n",
            names = names
        ));
        out.push_str(&format!(
            "                a.kind = {}; a.{single_wire} = {names}[0];\n",
            js_quote(single.kind),
            single_wire = single_wire,
            names = names
        ));
        out.push_str("            } else {\n");
        out.push_str(&format!(
            "                a.kind = {}; a.{list_wire} = {names};\n",
            js_quote(to),
            list_wire = list_wire,
            names = names
        ));
        out.push_str("            }\n");
        out.push_str(&format!("            delete a.{names};\n", names = names));
    } else if let (Some(to), Some(from_to)) = (g.to_kind, g.from_to_kind) {
        out.push_str(&format!(
            "            a.kind = a.from ? {} : {};\n",
            js_quote(from_to),
            js_quote(to)
        ));
        let entry = g
            .usable
            .iter()
            .find(|d| !d.fields.iter().any(|f| f.friendly == "from"))
            .or_else(|| g.usable.first())
            .copied()
            .expect("usable entry");
        render_js_fields(out, entry.fields);
    } else {
        // single wire kind for this friendly kind
        let entry = g
            .usable
            .first()
            .copied()
            .or_else(|| ACTION_SPECS.iter().find(|d| d.friendly == g.friendly))
            .expect("entry for friendly kind");
        out.push_str(&format!("            a.kind = {};\n", js_quote(entry.kind)));
        render_js_fields(out, entry.fields);
    }
    out.push_str("            break;\n");
    out.push_str("        }\n");
}

fn render_js_fields(out: &mut String, fields: &[FieldDef]) {
    // struct fields are grouped per wire struct, then deleted. Members mapped
    // from an optional friendly field (`RustConv::StructOptStr`) are assigned
    // conditionally: an absent/empty friendly value stays absent on the wire,
    // so the wire JSON shape matches the friendly shape.
    let mut structs: Vec<(&'static str, Vec<(&'static str, &'static str, JsSubConv, bool)>)> =
        Vec::new();
    for f in fields {
        match f.js {
            JsConv::StructField(s, sub, subconv) => {
                let optional = matches!(f.rust, RustConv::StructOptStr(..));
                if let Some(g) = structs.iter_mut().find(|(name, _)| *name == s) {
                    g.1.push((sub, f.friendly, subconv, optional));
                } else {
                    structs.push((s, vec![(sub, f.friendly, subconv, optional)]));
                }
            }
            _ => render_js_field(out, f),
        }
    }
    for (s, members) in structs {
        let mut parts = Vec::new();
        // (declaration, conditional assignment) pairs: the friendly value is
        // captured into a local BEFORE the fields are deleted, then the member
        // is assigned only when the value is present (absent/empty stays
        // absent on the wire, so the wire JSON shape matches the friendly
        // shape).
        let mut conditionals: Vec<(String, String)> = Vec::new();
        for (sub, friendly, subconv, optional) in &members {
            if *optional {
                let tmp = format!("{friendly}_opt");
                let expr = match subconv {
                    JsSubConv::Keep(d) => format!("{tmp} ?? {}", js_quote(d)),
                    JsSubConv::ToString(d) => format!("String({tmp} ?? {})", js_quote(d)),
                    JsSubConv::HexOrKeep(d) => format!("toHexOrKeep({tmp} ?? {})", js_quote(d)),
                    JsSubConv::Hex => format!("toHex({tmp})"),
                };
                conditionals.push((
                    format!("        const {tmp} = a.{friendly};"),
                    format!(
                        "        if ({tmp} !== undefined && {tmp} !== null && {tmp} !== \"\") {{ a.{s}.{sub} = {expr}; }}"
                    ),
                ));
            } else {
                parts.push(format!(
                    "                {}: {}",
                    js_quote(sub),
                    render_js_subconv(*subconv, friendly)
                ));
            }
        }
        for (decl, _) in &conditionals {
            out.push_str(&format!("{decl}\n"));
        }
        out.push_str(&format!("            a.{s} = {{\n"));
        out.push_str(&parts.join(",\n"));
        if !parts.is_empty() {
            out.push_str("\n");
        }
        out.push_str("            };\n");
        for (_, friendly, _, _) in &members {
            out.push_str(&format!("            delete a.{friendly};\n"));
        }
        for (_, assignment) in &conditionals {
            out.push_str(&format!("{assignment}\n"));
        }
    }
}

fn render_js_field(out: &mut String, f: &FieldDef) {
    match f.js {
        JsConv::Noop => {}
        JsConv::Rename(w) if w == f.friendly => {}
        JsConv::Rename(w) => {
            out.push_str(&format!("            a.{w} = a.{};\n", f.friendly));
            out.push_str(&format!("            delete a.{};\n", f.friendly));
        }
        JsConv::RenameDef(w, def) if w == f.friendly => {
            out.push_str(&format!(
                "            a.{w} = a.{w} ?? {};\n",
                js_quote(def)
            ));
        }
        JsConv::RenameDef(w, def) => {
            out.push_str(&format!(
                "            a.{w} = a.{} ?? {};\n",
                f.friendly,
                js_quote(def)
            ));
            if w != f.friendly {
                out.push_str(&format!("            delete a.{};\n", f.friendly));
            }
        }
        JsConv::RenameDefNum(w, def) => {
            if w == f.friendly {
                out.push_str(&format!("            a.{w} = a.{w} ?? {def};\n"));
            } else {
                out.push_str(&format!("            a.{w} = a.{} ?? {def};\n", f.friendly));
                out.push_str(&format!("            delete a.{};\n", f.friendly));
            }
        }
        JsConv::ToString(w, def) => {
            out.push_str(&format!(
                "            a.{w} = String(a.{} ?? {});\n",
                f.friendly,
                js_quote(def)
            ));
            if w != f.friendly {
                out.push_str(&format!("            delete a.{};\n", f.friendly));
            }
        }
        JsConv::NumList(w) => {
            out.push_str(&format!(
                "            a.{w} = (a.{} ?? []).map(Number);\n",
                f.friendly
            ));
            if w != f.friendly {
                out.push_str(&format!("            delete a.{};\n", f.friendly));
            }
        }

        JsConv::Hex(w) => {
            if w == f.friendly {
                out.push_str(&format!("            a.{w} = toHex(a.{w});\n"));
            } else {
                out.push_str(&format!("            a.{w} = toHex(a.{});\n", f.friendly));
                out.push_str(&format!("            delete a.{};\n", f.friendly));
            }
        }
        JsConv::HexList(w) => {
            out.push_str(&format!(
                "            a.{w} = (a.{} ?? []).map(toHex);\n",
                f.friendly
            ));
            if w != f.friendly {
                out.push_str(&format!("            delete a.{};\n", f.friendly));
            }
        }
        JsConv::HexOrKeep(w, def) => {
            if w == f.friendly {
                out.push_str(&format!(
                    "            a.{w} = toHexOrKeep(a.{w} ?? {});\n",
                    js_quote(def)
                ));
            } else {
                out.push_str(&format!(
                    "            a.{w} = toHexOrKeep(a.{} ?? {});\n",
                    f.friendly,
                    js_quote(def)
                ));
                out.push_str(&format!("            delete a.{};\n", f.friendly));
            }
        }
        JsConv::Strip0x(w, def) => {
            if w == f.friendly {
                out.push_str(&format!(
                    "            a.{w} = (a.{w} ?? {}).replace(/^0x/, \"\");\n",
                    js_quote(def)
                ));
            } else {
                out.push_str(&format!(
                    "            a.{w} = (a.{} ?? {}).replace(/^0x/, \"\");\n",
                    f.friendly,
                    js_quote(def)
                ));
                out.push_str(&format!("            delete a.{};\n", f.friendly));
            }
        }
        JsConv::HexSingle(_) => {} // only in the single-to flow, not per-field
        JsConv::StructField(..) => {} // grouped in render_js_fields
    }
}

fn render_js_subconv(subconv: JsSubConv, friendly: &str) -> String {
    match subconv {
        JsSubConv::Keep(d) => format!("a.{friendly} ?? {}", js_quote(d)),
        JsSubConv::ToString(d) => format!("String(a.{friendly} ?? {})", js_quote(d)),
        JsSubConv::HexOrKeep(d) => format!("toHexOrKeep(a.{friendly} ?? {})", js_quote(d)),
        JsSubConv::Hex => format!("toHex(a.{friendly})"),
    }
}

// ================================ TS discriminated union ================================

/// `actionspec.d.ts`: the friendly `ActionSpec` discriminated union (types
/// only; the runtime adapter is in `actionspec.mjs`).
pub fn render_actionspec_dts() -> String {
    let mut out = String::new();
    out.push_str("// GENERATED by `sdk_codegen` (cargo run -p sdk --bin sdk_codegen). DO NOT EDIT.\n");
    out.push_str("// Friendly ActionSpec union derived from Rust `sdk::actionspec::ACTION_SPECS`.\n\n");
    let mut variants: Vec<(&'static str, &'static [FieldDef])> = Vec::new();
    for def in ACTION_SPECS {
        if !variants.iter().any(|(v, _)| *v == def.variant) {
            variants.push((def.variant, def.fields));
        }
    }
    let kinds: Vec<String> = variants
        .iter()
        .map(|(variant, _)| {
            let friendly = ACTION_SPECS
                .iter()
                .find(|d| d.variant == *variant)
                .map(|d| d.friendly)
                .unwrap_or(variant);
            js_quote(friendly)
        })
        .collect();
    out.push_str(&format!(
        "export type FriendlyActionKind = {};\n\n",
        kinds.join(" | ")
    ));
    for (variant, fields) in &variants {
        let friendly = ACTION_SPECS
            .iter()
            .find(|d| d.variant == *variant)
            .map(|d| d.friendly)
            .unwrap_or(variant);
        out.push_str(&format!("export interface {variant}Spec {{\n"));
        out.push_str(&format!("    kind: {};\n", js_quote(friendly)));
        for f in *fields {
            if let Some(decl) = ts_field_decl(f) {
                out.push_str(&format!("    {decl};\n"));
            }
        }
        out.push_str("}\n\n");
    }
    let names: Vec<String> = variants.iter().map(|(v, _)| format!("{v}Spec")).collect();
    out.push_str("// Any action kind the codec schema registry knows can be built in its\n");
    out.push_str("// wire shape (design A) through the generic `RawAction` path; the wire\n");
    out.push_str("// fields are documented by `ACTION_METADATA` in codec.ts.\n");
    out.push_str("export interface RawActionSpec {\n");
    out.push_str("    kind: string;\n");
    out.push_str("    [field: string]: unknown;\n");
    out.push_str("}\n\n");
    out.push_str(&format!(
        "export type ActionSpec = {} | RawActionSpec;\n",
        names.join(" | ")
    ));
    out
}

fn ts_field_decl(f: &FieldDef) -> Option<String> {
    let (optional, ty) = match f.rust {
        RustConv::ConstNone => (true, "string".to_owned()),
        RustConv::SomeStr(_) => (true, "string".to_owned()),
        RustConv::Opt(_, "str") => (true, "string".to_owned()),
        RustConv::Opt(_, _) => (true, "number".to_owned()),
        RustConv::Str(_) | RustConv::Dia(_) | RustConv::DiaName => (false, "string".to_owned()),
        RustConv::StructStr(..) | RustConv::StructReadable(..) | RustConv::AssetStr(_) => {
            (false, "string".to_owned())
        }
        RustConv::StructOptStr(..) => (true, "string".to_owned()),
        RustConv::Num(_) | RustConv::AssetNum(_) => (false, "number".to_owned()),
        RustConv::StrList(_) | RustConv::DiaList | RustConv::DiaSingle => {
            (false, "string[]".to_owned())
        }
        RustConv::NumList(_) => (false, "number[]".to_owned()),
        RustConv::ConstEmpty => return None,
    };
    Some(format!(
        "{}{}: {ty}",
        f.friendly,
        if optional { "?" } else { "" }
    ))
}

// ================================ regeneration lock ================================

#[cfg(test)]
mod tests {
    use super::*;

    /// The checked-in generated artifacts must equal what the Rust sources
    /// produce; a stale artifact fails here (run
    /// `cargo run -p sdk --bin sdk_codegen` to regenerate).
    #[test]
    fn generated_artifacts_match() {
        let manifest = env!("CARGO_MANIFEST_DIR");
        for (name, rendered) in [
            ("op_tables.mjs", render_op_tables()),
            ("operations.mjs", render_operations_mjs()),
            ("actionspec.mjs", render_actionspec_mjs()),
            ("actionspec.d.ts", render_actionspec_dts()),
        ] {
            let path = format!("{manifest}/js/generated/{name}");
            let on_disk = std::fs::read_to_string(&path)
                .unwrap_or_else(|e| panic!("read {path}: {e} (run sdk_codegen)"));
            assert_eq!(
                on_disk, rendered,
                "{name} drifted from the Rust sources; regenerate via `cargo run -p sdk --bin sdk_codegen`"
            );
        }
    }
}
