//! Binary view encode/decode layer — the wasm core is JSON-free.
//!
//! Response bodies and complex request objects (Review/Policy/SigningRequest/
//! SignatureProof/MessagePrepareParams/TransactionJson) travel as `bjson`
//! field streams (`crate::bjson`). The only JSON that remains here is the
//! hand-written error-detail builder (`esc`/`q`/`obj`/`arr`/`kv`): the error
//! envelope's `detail` is a small human-readable string produced by the
//! attach/error paths, a few `format!` calls with no field JSON engine behind
//! them. Semantic values (amounts/addresses/hex) stay strings; parsing belongs
//! to Rust's consensus layer (design A).

use sys::{Ret, errf};

use crate::audit::{ActionDesc, PayloadDesc, TransferDesc};
use crate::build::BuiltTransaction;
use crate::inspect::{
    HeightRangeDesc, InspectContext, Review, SignatureEntry, TransactionJson,
};
use crate::policy::{Policy, PolicyDecision};
use crate::profile::{
    AbiVersion, Capabilities, CodecProfile, FeatureItem, LimitsProfile,
    ProtocolParamsProfile,
};
use crate::attach::{
    AttachResult, SignatureProof, SignatureReport, SigningRequest, VerifyResult,
};
use crate::bjson::{BVal, Bw, opt, parse, req};
use crate::message::{MessagePrepareParams, MessageVerifyResult};
use crate::account::{AddressFromPublicKeyResult, VerifyAddressResult};
use crate::amount::ParsedAmount;

// ================================ error-detail JSON builders ================================
// Retained only for `SdkError.detail` (a string in the binary envelope) and
// native-side tests; not the field JSON engine.

// ================================ binary layout tables ================================
// Every `impl_sdk_bin!` declaration emits `BIN_FIELDS` — the declarative field
// layout that drives the JS facade pack/unpack (generated by `sdk_codegen`).
// The layout and the Rust writer/reader come from the same macro invocation,
// so the two languages can never drift; `PayloadDesc` (tagged enum) keeps a
// hand-written writer but its layout is declared here and locked by a test.

/// One binary field of an SDK object layout.
#[derive(Debug, Clone, Copy)]
pub(crate) struct BinField {
    pub name: &'static str,
    pub kind: BinKind,
    /// JS-side default literal rendered for required fields when the caller
    /// value is absent (encode) or the wire field is missing (decode);
    /// `None` renders the kind's natural default ("" / 0 / false / []).
    pub js_default: Option<&'static str>,
}

#[derive(Debug, Clone, Copy)]
pub(crate) enum BinKind {
    Str,
    OptStr,
    StrDef,
    U64,
    OptU64,
    U64Def,
    U32,
    OptU32,
    U32Def,
    U8,
    OptU8,
    U8Def,
    Bool,
    OptBool,
    BoolDef(bool),
    StrArr,
    OptStrArr,
    U64Arr,
    OptU64Arr,
    U32Arr,
    OptU32Arr,
    U16Arr,
    OptU16Arr,
    Usize,
    UsizeDef,
    U16,
    /// Nested view object referenced by its BIN_TYPES js name (the codegen
    /// resolves the tree by name, so self-referential layouts are acyclic).
    Obj(&'static str),
    OptObj(&'static str),
    ObjArr(&'static str),
    OptObjArr(&'static str),
    /// Tagged enum (PayloadDesc): the wire carries a `type` tag plus the
    /// selected variant's fields.
    Tagged(&'static [TaggedVariant]),
}

#[derive(Debug, Clone, Copy)]
pub(crate) struct TaggedVariant {
    pub tag: &'static str,
    pub fields: &'static [BinField],
}

/// One layout-typed object and the directions the JS facade needs it in.
#[derive(Debug, Clone, Copy)]
pub(crate) struct BinType {
    /// JS identifier base (renders `encodeX`/`decodeX`).
    pub js: &'static str,
    pub dir: BinDir,
    pub fields: &'static [BinField],
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum BinDir {
    To,
    From,
    Both,
}

/// Every layout-driven object, single list for the JS code generator.
pub(crate) const BIN_TYPES: &[BinType] = &[
    BinType { js: "InspectContext", dir: BinDir::Both, fields: InspectContext::BIN_FIELDS },
    BinType { js: "HeightRangeDesc", dir: BinDir::Both, fields: HeightRangeDesc::BIN_FIELDS },
    BinType { js: "SignatureEntry", dir: BinDir::Both, fields: SignatureEntry::BIN_FIELDS },
    BinType { js: "SignatureProof", dir: BinDir::Both, fields: SignatureProof::BIN_FIELDS },
    BinType { js: "PolicyDecision", dir: BinDir::Both, fields: PolicyDecision::BIN_FIELDS },
    BinType { js: "PayloadDesc", dir: BinDir::Both, fields: PayloadDesc::BIN_FIELDS },
    BinType { js: "TransferDesc", dir: BinDir::Both, fields: TransferDesc::BIN_FIELDS },
    BinType { js: "ActionDesc", dir: BinDir::Both, fields: ActionDesc::BIN_FIELDS },
    BinType { js: "Review", dir: BinDir::Both, fields: Review::BIN_FIELDS },
    BinType { js: "Policy", dir: BinDir::Both, fields: Policy::BIN_FIELDS },
    BinType { js: "SigningRequest", dir: BinDir::Both, fields: SigningRequest::BIN_FIELDS },
    BinType { js: "TransactionJson", dir: BinDir::Both, fields: TransactionJson::BIN_FIELDS },
    BinType {
        js: "VerifyAddressResult",
        dir: BinDir::To,
        fields: crate::account::VerifyAddressResult::BIN_FIELDS,
    },
    BinType {
        js: "AddressFromPublicKeyResult",
        dir: BinDir::To,
        fields: crate::account::AddressFromPublicKeyResult::BIN_FIELDS,
    },
    BinType { js: "ParsedAmount", dir: BinDir::To, fields: crate::amount::ParsedAmount::BIN_FIELDS },
    BinType {
        js: "MessageVerifyResult",
        dir: BinDir::To,
        fields: crate::message::MessageVerifyResult::BIN_FIELDS,
    },
    BinType {
        js: "ProtocolParamsProfile",
        dir: BinDir::To,
        fields: ProtocolParamsProfile::BIN_FIELDS,
    },
    BinType { js: "LimitsProfile", dir: BinDir::To, fields: LimitsProfile::BIN_FIELDS },
    BinType { js: "CodecProfile", dir: BinDir::To, fields: CodecProfile::BIN_FIELDS },
    BinType { js: "AbiVersion", dir: BinDir::To, fields: AbiVersion::BIN_FIELDS },
    BinType { js: "FeatureItem", dir: BinDir::To, fields: FeatureItem::BIN_FIELDS },
    BinType { js: "Capabilities", dir: BinDir::To, fields: Capabilities::BIN_FIELDS },
    BinType { js: "SdkVersion", dir: BinDir::To, fields: SdkVersion::BIN_FIELDS },
    BinType { js: "AttachResult", dir: BinDir::To, fields: AttachResult::BIN_FIELDS },
    BinType { js: "VerifyResult", dir: BinDir::To, fields: VerifyResult::BIN_FIELDS },
    BinType { js: "SignatureReport", dir: BinDir::To, fields: SignatureReport::BIN_FIELDS },
    BinType { js: "BuiltTransaction", dir: BinDir::To, fields: BuiltTransaction::BIN_FIELDS },
    BinType {
        js: "AmountFormatResult",
        dir: BinDir::To,
        fields: AmountFormatResult::BIN_FIELDS,
    },
    BinType {
        js: "MessagePrepareParams",
        dir: BinDir::From,
        fields: crate::message::MessagePrepareParams::BIN_FIELDS,
    },
];

/// JSON string escaping (for `"`, `\`, and control characters).
pub(crate) fn esc(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => {
                out.push_str(&format!("\\u{:04x}", c as u32));
            }
            c => out.push(c),
        }
    }
    out
}

/// Quoted string `"..."`.
pub(crate) fn q(s: &str) -> String {
    format!("\"{}\"", esc(s))
}

/// Object `{"k":v,...}` (empty-string entries are skipped, used for Option fields).
pub(crate) fn obj(parts: Vec<String>) -> String {
    let filtered: Vec<&str> = parts.iter().filter(|p| !p.is_empty()).map(|s| s.as_str()).collect();
    format!("{{{}}}", filtered.join(","))
}

/// Array `[...]`.
pub(crate) fn arr(parts: Vec<String>) -> String {
    format!("[{}]", parts.join(","))
}

/// Key-value pair `"k":v`.
pub(crate) fn kv(key: &str, value: String) -> String {
    format!("\"{}\":{}", esc(key), value)
}

/// Option field: None returns an empty string (filtered out by `obj`).
pub(crate) fn kv_opt(key: &str, value: Option<String>) -> String {
    value.map(|v| kv(key, v)).unwrap_or_default()
}

// ================================ simple-object binary derive ================================
// Types whose binary shape is a plain field list get both directions generated
// here; the rest (Review/ActionDesc/PayloadDesc/Policy/CodecProfile/...) keep
// hand-written impls below because their layout carries structure.

macro_rules! sdk_bin_kv {
    ($w:ident, $self:ident, $field:ident, str) => {
        $w.str(stringify!($field), &$self.$field)
    };
    ($w:ident, $self:ident, $field:ident, opt_str) => {
        $w.opt_str(stringify!($field), $self.$field.as_deref())
    };
    ($w:ident, $self:ident, $field:ident, u64) => {
        $w.u64(stringify!($field), $self.$field)
    };
    ($w:ident, $self:ident, $field:ident, opt_u64) => {
        $w.opt_u64(stringify!($field), $self.$field)
    };
    ($w:ident, $self:ident, $field:ident, u32) => {
        $w.u32(stringify!($field), $self.$field)
    };
    ($w:ident, $self:ident, $field:ident, opt_u32) => {
        $w.opt_u32(stringify!($field), $self.$field)
    };
    ($w:ident, $self:ident, $field:ident, u8) => {
        $w.u8(stringify!($field), $self.$field)
    };
    ($w:ident, $self:ident, $field:ident, opt_u8) => {
        if let Some(v) = $self.$field {
            $w.u8(stringify!($field), v);
        }
    };
    ($w:ident, $self:ident, $field:ident, bool) => {
        $w.bool(stringify!($field), $self.$field)
    };
    ($w:ident, $self:ident, $field:ident, opt_bool) => {
        if let Some(v) = $self.$field {
            $w.bool(stringify!($field), v);
        }
    };
    ($w:ident, $self:ident, $field:ident, str_arr) => {
        $w.str_arr(stringify!($field), &$self.$field)
    };
    ($w:ident, $self:ident, $field:ident, opt_str_arr) => {
        if let Some(v) = &$self.$field {
            $w.str_arr(stringify!($field), v);
        }
    };
    ($w:ident, $self:ident, $field:ident, u64_arr) => {
        $w.u64_arr(stringify!($field), &$self.$field)
    };
    ($w:ident, $self:ident, $field:ident, u32_arr) => {
        $w.u32_arr(stringify!($field), &$self.$field)
    };
    ($w:ident, $self:ident, $field:ident, opt_u32_arr) => {
        if let Some(v) = &$self.$field {
            $w.u32_arr(stringify!($field), v);
        }
    };
    ($w:ident, $self:ident, $field:ident, usize) => {
        $w.u64(stringify!($field), $self.$field as u64)
    };
    ($w:ident, $self:ident, $field:ident, u16) => {
        $w.u32(stringify!($field), $self.$field as u32)
    };
    ($w:ident, $self:ident, $field:ident, u16_arr) => {
        $w.u32_arr(
            stringify!($field),
            &$self.$field.iter().map(|v| *v as u32).collect::<Vec<_>>(),
        )
    };
    ($w:ident, $self:ident, $field:ident, opt_u16_arr) => {
        if let Some(v) = &$self.$field {
            $w.u32_arr(stringify!($field), &v.iter().map(|x| *x as u32).collect::<Vec<_>>());
        }
    };
    ($w:ident, $self:ident, $field:ident, str_def) => {
        $w.str(stringify!($field), &$self.$field)
    };
    ($w:ident, $self:ident, $field:ident, u64_def) => {
        $w.u64(stringify!($field), $self.$field)
    };
    ($w:ident, $self:ident, $field:ident, u32_def) => {
        $w.u32(stringify!($field), $self.$field)
    };
    ($w:ident, $self:ident, $field:ident, u8_def) => {
        $w.u8(stringify!($field), $self.$field)
    };
    ($w:ident, $self:ident, $field:ident, bool_def_true) => {
        $w.bool(stringify!($field), $self.$field)
    };
    ($w:ident, $self:ident, $field:ident, bool_def_false) => {
        $w.bool(stringify!($field), $self.$field)
    };
    ($w:ident, $self:ident, $field:ident, usize_def) => {
        $w.u64(stringify!($field), $self.$field as u64)
    };
    ($w:ident, $self:ident, $field:ident, obj $t:ty) => {
        $w.obj_from_body(stringify!($field), <$t>::to_binary_body(&$self.$field));
    };
    ($w:ident, $self:ident, $field:ident, opt_obj $t:ty) => {
        if let Some(v) = &$self.$field {
            $w.obj_from_body(stringify!($field), <$t>::to_binary_body(v));
        }
    };
    ($w:ident, $self:ident, $field:ident, obj_arr $t:ty) => {
        $w.obj_arr(
            stringify!($field),
            &$self.$field.iter().map(|x| <$t>::to_binary_body(x)).collect::<Vec<_>>(),
        );
    };
    ($w:ident, $self:ident, $field:ident, opt_obj_arr $t:ty) => {
        if let Some(v) = &$self.$field {
            $w.obj_arr(
                stringify!($field),
                &v.iter().map(|x| <$t>::to_binary_body(x)).collect::<Vec<_>>(),
            );
        }
    };
}

macro_rules! sdk_bin_expr {
    ($fields:ident, $field:ident, str) => {
        req(&$fields, stringify!($field))?.str()?.to_owned()
    };
    ($fields:ident, $field:ident, opt_str) => {
        opt(&$fields, stringify!($field))
            .map(|v| v.str().map(str::to_owned))
            .transpose()?
    };
    ($fields:ident, $field:ident, u64) => {
        req(&$fields, stringify!($field))?.u64()?
    };
    ($fields:ident, $field:ident, opt_u64) => {
        opt(&$fields, stringify!($field)).map(|v| v.u64()).transpose()?
    };
    ($fields:ident, $field:ident, u32) => {
        req(&$fields, stringify!($field))?.u32()?
    };
    ($fields:ident, $field:ident, opt_u32) => {
        opt(&$fields, stringify!($field)).map(|v| v.u32()).transpose()?
    };
    ($fields:ident, $field:ident, u8) => {
        req(&$fields, stringify!($field))?.u8()?
    };
    ($fields:ident, $field:ident, opt_u8) => {
        opt(&$fields, stringify!($field)).map(|v| v.u8()).transpose()?
    };
    ($fields:ident, $field:ident, bool) => {
        req(&$fields, stringify!($field))?.bool()?
    };
    ($fields:ident, $field:ident, opt_bool) => {
        opt(&$fields, stringify!($field)).map(|v| v.bool()).transpose()?
    };
    ($fields:ident, $field:ident, str_arr) => {
        opt(&$fields, stringify!($field))
            .map(|v| v.str_arr().map(|a| a.into_iter().map(str::to_owned).collect()))
            .transpose()?
            .unwrap_or_default()
    };
    ($fields:ident, $field:ident, opt_str_arr) => {
        opt(&$fields, stringify!($field))
            .map(|v| v.str_arr().map(|a| a.into_iter().map(str::to_owned).collect()))
            .transpose()?
    };
    ($fields:ident, $field:ident, u64_arr) => {
        opt(&$fields, stringify!($field))
            .map(|v| v.u64_arr())
            .transpose()?
            .unwrap_or_default()
    };
    ($fields:ident, $field:ident, u32_arr) => {
        opt(&$fields, stringify!($field))
            .map(|v| v.u32_arr())
            .transpose()?
            .unwrap_or_default()
    };
    ($fields:ident, $field:ident, opt_u32_arr) => {
        opt(&$fields, stringify!($field)).map(|v| v.u32_arr()).transpose()?
    };
    ($fields:ident, $field:ident, usize) => {
        req(&$fields, stringify!($field))?.u64().map(|v| v as usize)?
    };
    ($fields:ident, $field:ident, u16) => {
        req(&$fields, stringify!($field))?.u32().map(|v| v as u16)?
    };
    ($fields:ident, $field:ident, u16_arr) => {
        opt(&$fields, stringify!($field))
            .map(|v| v.u32_arr().map(|a| a.into_iter().map(|x| x as u16).collect()))
            .transpose()?
            .unwrap_or_default()
    };
    ($fields:ident, $field:ident, opt_u16_arr) => {
        opt(&$fields, stringify!($field))
            .map(|v| v.u32_arr().map(|a| a.into_iter().map(|x| x as u16).collect()))
            .transpose()?
    };
    ($fields:ident, $field:ident, str_def) => {
        opt(&$fields, stringify!($field))
            .map(|v| v.str().map(str::to_owned))
            .transpose()?
            .unwrap_or_default()
    };
    ($fields:ident, $field:ident, u64_def) => {
        opt(&$fields, stringify!($field))
            .map(|v| v.u64())
            .transpose()?
            .unwrap_or_default()
    };
    ($fields:ident, $field:ident, u32_def) => {
        opt(&$fields, stringify!($field))
            .map(|v| v.u32())
            .transpose()?
            .unwrap_or_default()
    };
    ($fields:ident, $field:ident, u8_def) => {
        opt(&$fields, stringify!($field))
            .map(|v| v.u8())
            .transpose()?
            .unwrap_or_default()
    };
    ($fields:ident, $field:ident, bool_def_true) => {
        opt(&$fields, stringify!($field))
            .map(|v| v.bool())
            .transpose()?
            .unwrap_or(true)
    };
    ($fields:ident, $field:ident, bool_def_false) => {
        opt(&$fields, stringify!($field))
            .map(|v| v.bool())
            .transpose()?
            .unwrap_or(false)
    };
    ($fields:ident, $field:ident, usize_def) => {
        opt(&$fields, stringify!($field))
            .map(|v| v.u64().map(|x| x as usize))
            .transpose()?
            .unwrap_or_default()
    };
    ($fields:ident, $field:ident, obj $t:ty) => {
        <$t>::from_binary(&reserialize_obj(req(&$fields, stringify!($field))?)?)?
    };
    ($fields:ident, $field:ident, opt_obj $t:ty) => {
        match opt(&$fields, stringify!($field)) {
            Some(v) => Some(<$t>::from_binary(&reserialize_obj(v)?)?),
            None => None,
        }
    };
    ($fields:ident, $field:ident, obj_arr $t:ty) => {
        match opt(&$fields, stringify!($field)) {
            Some(v) => v
                .obj_arr()?
                .into_iter()
                .map(|item| <$t>::from_binary(&reserialize_fields(item)?))
                .collect::<Ret<Vec<_>>>()?,
            None => vec![],
        }
    };
    ($fields:ident, $field:ident, opt_obj_arr $t:ty) => {
        match opt(&$fields, stringify!($field)) {
            Some(v) => Some(
                v.obj_arr()?
                    .into_iter()
                    .map(|item| <$t>::from_binary(&reserialize_fields(item)?))
                    .collect::<Ret<Vec<_>>>()?,
            ),
            None => None,
        }
    };
}

/// Layout kind of one field (mirrors the `sdk_bin_kv!`/`sdk_bin_expr!` arms).
/// The optional `$arg:ty` carries the nested view type (`obj X`, `obj_arr X`).
macro_rules! bin_kind {
    (str) => { BinKind::Str };
    (opt_str) => { BinKind::OptStr };
    (str_def) => { BinKind::StrDef };
    (u64) => { BinKind::U64 };
    (opt_u64) => { BinKind::OptU64 };
    (u64_def) => { BinKind::U64Def };
    (u32) => { BinKind::U32 };
    (opt_u32) => { BinKind::OptU32 };
    (u32_def) => { BinKind::U32Def };
    (u8) => { BinKind::U8 };
    (opt_u8) => { BinKind::OptU8 };
    (u8_def) => { BinKind::U8Def };
    (bool) => { BinKind::Bool };
    (opt_bool) => { BinKind::OptBool };
    (bool_def_true) => { BinKind::BoolDef(true) };
    (bool_def_false) => { BinKind::BoolDef(false) };
    (str_arr) => { BinKind::StrArr };
    (opt_str_arr) => { BinKind::OptStrArr };
    (u64_arr) => { BinKind::U64Arr };
    (opt_u64_arr) => { BinKind::OptU64Arr };
    (u32_arr) => { BinKind::U32Arr };
    (opt_u32_arr) => { BinKind::OptU32Arr };
    (u16_arr) => { BinKind::U16Arr };
    (opt_u16_arr) => { BinKind::OptU16Arr };
    (usize) => { BinKind::Usize };
    (usize_def) => { BinKind::UsizeDef };
    (u16) => { BinKind::U16 };
    (obj $t:ty) => { BinKind::Obj(stringify!($t)) };
    (opt_obj $t:ty) => { BinKind::OptObj(stringify!($t)) };
    (obj_arr $t:ty) => { BinKind::ObjArr(stringify!($t)) };
    (opt_obj_arr $t:ty) => { BinKind::OptObjArr(stringify!($t)) };
}

/// Generate `to_binary_body`/`from_binary`/`BIN_FIELDS` for a binary view type
/// (modes: `to`, `from`, `both`). Field kinds: `str`/`opt_str`/`str_def`/
/// `u64`/`opt_u64`/`u64_def`/`u32`/`opt_u32`/`u32_def`/`u8`/`opt_u8`/`u8_def`/
/// `bool`/`opt_bool`/`bool_def(d)`/`str_arr`/`opt_str_arr`/`u64_arr`/
/// `opt_u64_arr`/`u32_arr`/`opt_u32_arr`/`u16_arr`/`opt_u16_arr`/`usize`/
/// `usize_def`/`u16`/`obj T`/`opt_obj T`/`obj_arr T`/`opt_obj_arr T`.
/// `BIN_FIELDS` is the single declarative layout for the generated JS facade
/// (same invocation as the writer/reader, so they can never drift).
macro_rules! impl_sdk_bin {
    ($ty:ty { $($field:ident : $kind:ident $($arg:ty)?),+ $(,)? } both) => {
        impl $ty {
            pub(crate) const BIN_FIELDS: &'static [BinField] = &[
                $(BinField { name: stringify!($field), kind: bin_kind!($kind $($arg)?), js_default: None }),+
            ];

            pub(crate) fn to_binary_body(&self) -> Vec<u8> {
                let mut w = Bw::new();
                $(sdk_bin_kv!(w, self, $field, $kind $($arg)?);)+
                w.into_inner()
            }

            pub(crate) fn from_binary(buf: &[u8]) -> sys::Ret<Self> {
                let fields = parse(buf)?;
                $(let $field = sdk_bin_expr!(fields, $field, $kind $($arg)?);)+
                Ok(Self { $($field),+ })
            }
        }
    };
    ($ty:ty { $($field:ident : $kind:ident $($arg:ty)?),+ $(,)? } to) => {
        impl $ty {
            pub(crate) const BIN_FIELDS: &'static [BinField] = &[
                $(BinField { name: stringify!($field), kind: bin_kind!($kind $($arg)?), js_default: None }),+
            ];

            pub(crate) fn to_binary_body(&self) -> Vec<u8> {
                let mut w = Bw::new();
                $(sdk_bin_kv!(w, self, $field, $kind $($arg)?);)+
                w.into_inner()
            }
        }
    };
    ($ty:ty { $($field:ident : $kind:ident $($arg:ty)?),+ $(,)? } from) => {
        impl $ty {
            pub(crate) const BIN_FIELDS: &'static [BinField] = &[
                $(BinField { name: stringify!($field), kind: bin_kind!($kind $($arg)?), js_default: None }),+
            ];

            pub(crate) fn from_binary(buf: &[u8]) -> sys::Ret<Self> {
                let fields = parse(buf)?;
                $(let $field = sdk_bin_expr!(fields, $field, $kind $($arg)?);)+
                Ok(Self { $($field),+ })
            }
        }
    };
}

// ================================ basic results ================================

impl_sdk_bin! {
    VerifyAddressResult { ok: bool, error: opt_str, address: opt_str } to
}
impl_sdk_bin! {
    AddressFromPublicKeyResult { address: str, version: u8 } to
}
impl_sdk_bin! {
    ParsedAmount { value: str, unit: u8, is_negative: bool } to
}
impl_sdk_bin! {
    MessageVerifyResult { ok: bool, address: opt_str, error: opt_str } to
}

// ================================ profile ================================

impl ProtocolParamsProfile {
    pub(crate) const BIN_FIELDS: &'static [BinField] = &[
        BinField { name: "ast_tree_depth_max", kind: BinKind::U64, js_default: None },
        BinField { name: "max_type3_signers", kind: BinKind::U64, js_default: None },
        BinField { name: "fee_purity_floor", kind: BinKind::U64, js_default: None },
        BinField { name: "diamond_form_flag", kind: BinKind::U64, js_default: None },
        // Flattened (activation, next) pairs; the JS facade reads the array
        // as-is (pairs are split by the upper layer when needed).
        BinField { name: "fee_purity_reductions", kind: BinKind::U64Arr, js_default: None },
    ];

    pub(crate) fn to_binary_body(&self) -> Vec<u8> {
        let mut w = Bw::new();
        w.u64("ast_tree_depth_max", self.ast_tree_depth_max as u64);
        w.u64("max_type3_signers", self.max_type3_signers as u64);
        w.u64("fee_purity_floor", self.fee_purity_floor);
        w.u64("diamond_form_flag", self.diamond_form_flag);
        // Reductions travel flattened (activation, next) alternating.
        let flat: Vec<u64> = self
            .fee_purity_reductions
            .iter()
            .flat_map(|(activation, next)| [*activation, *next])
            .collect();
        w.u64_arr("fee_purity_reductions", &flat);
        w.into_inner()
    }
}

impl_sdk_bin! {
    LimitsProfile { max_tx_size: usize, tx_actions_max: usize, hacd_wire_max: usize } to
}

impl_sdk_bin! {
    CodecProfile {
        schema: str,
        sdk_version: str,
        fullnode_commit: str,
        protocol_params: obj ProtocolParamsProfile,
        limits: obj LimitsProfile,
        registered_kinds: u16_arr,
        schema_hash: str,
        profile_hash: str,
    } to
}

impl_sdk_bin! {
    AbiVersion { major: u32, minor: u32 } to
}
impl_sdk_bin! {
    FeatureItem { id: str, version: u32 } to
}

impl_sdk_bin! {
    Capabilities {
        schema: str,
        package_version: str,
        abi: obj AbiVersion,
        codec_profile_hash: str,
        features: obj_arr FeatureItem,
    } to
}

/// The `system.sdk_version` response body (declared here so its layout is
/// part of the generated facade like every other response).
#[derive(Debug, Clone, PartialEq)]
pub(crate) struct SdkVersion {
    pub schema: String,
    pub package_version: String,
    pub abi: AbiVersion,
}

impl_sdk_bin! {
    SdkVersion { schema: str, package_version: str, abi: obj AbiVersion } to
}

/// The `amount.format_protocol` response body (`{value}`).
#[derive(Debug, Clone, PartialEq)]
pub(crate) struct AmountFormatResult {
    pub value: String,
}

impl_sdk_bin! {
    AmountFormatResult { value: str } to
}

// ================================ audit ================================

impl PayloadDesc {
    /// Tagged-enum layout: the wire `type` tag plus the selected variant's
    /// fields. The Rust writer/reader stay hand-written (enum dispatch); the
    /// layout drives the generated JS facade and is locked by
    /// `payload_desc_layout_matches_writer`.
    pub(crate) const BIN_FIELDS: &'static [BinField] = &[BinField {
        name: "type",
        kind: BinKind::Tagged(&[
            // js_default None: the type tag is always written by the encoder
            TaggedVariant {
                tag: "hac",
                fields: &[BinField {
                    name: "amount",
                    kind: BinKind::Str,
                    js_default: Some("0"),
                }],
            },
            TaggedVariant {
                tag: "satoshi",
                fields: &[BinField {
                    name: "atoms",
                    kind: BinKind::Str,
                    js_default: Some("0"),
                }],
            },
            TaggedVariant {
                tag: "hacd",
                fields: &[
                    BinField { name: "count", kind: BinKind::U32, js_default: None },
                    BinField { name: "names", kind: BinKind::StrArr, js_default: None },
                ],
            },
            TaggedVariant {
                tag: "asset",
                fields: &[
                    BinField { name: "serial", kind: BinKind::Str, js_default: None },
                    BinField {
                        name: "atoms",
                        kind: BinKind::Str,
                        js_default: Some("0"),
                    },
                ],
            },
        ]),
        js_default: None,
    }];

    pub(crate) fn to_binary_body(&self) -> Vec<u8> {
        let mut w = Bw::new();
        match self {
            PayloadDesc::Hac { amount } => {
                w.str("type", "hac");
                w.str("amount", amount);
            }
            PayloadDesc::Satoshi { atoms } => {
                w.str("type", "satoshi");
                w.str("atoms", atoms);
            }
            PayloadDesc::Hacd { count, names } => {
                w.str("type", "hacd");
                w.u32("count", *count);
                w.str_arr("names", names);
            }
            PayloadDesc::Asset { serial, atoms } => {
                w.str("type", "asset");
                w.str("serial", serial);
                w.str("atoms", atoms);
            }
        }
        w.into_inner()
    }

    pub(crate) fn from_binary(buf: &[u8]) -> Ret<Self> {
        Self::from_binary_fields(&parse(buf)?)
    }

    fn from_binary_fields(fields: &[(&str, BVal)]) -> Ret<Self> {
        match req(fields, "type")?.str()? {
            "hac" => Ok(PayloadDesc::Hac {
                amount: req(fields, "amount")?.str()?.to_owned(),
            }),
            "satoshi" => Ok(PayloadDesc::Satoshi {
                atoms: req(fields, "atoms")?.str()?.to_owned(),
            }),
            "hacd" => Ok(PayloadDesc::Hacd {
                count: req(fields, "count")?.u32()?,
                names: opt(fields, "names")
                    .map(|v| v.str_arr().map(|a| a.into_iter().map(str::to_owned).collect()))
                    .transpose()?
                    .unwrap_or_default(),
            }),
            "asset" => Ok(PayloadDesc::Asset {
                serial: req(fields, "serial")?.str()?.to_owned(),
                atoms: req(fields, "atoms")?.str()?.to_owned(),
            }),
            other => errf!("unknown payload type {}", other),
        }
    }
}

impl_sdk_bin! {
    TransferDesc {
        schema: str_def,
        from: opt_str,
        to: str,
        payload: obj PayloadDesc,
    } both
}

impl_sdk_bin! {
    ActionDesc {
        schema: str_def,
        index: usize_def,
        path: str_def,
        kind: u16,
        name: opt_str,
        scope: str_def,
        raw: str,
        protocol_valid: bool_def_true,
        auditability: str_def,
        audit_notes: str_arr,
        blob: bool_def_false,
        transfer: opt_obj TransferDesc,
        children: opt_obj_arr ActionDesc,
    } both
}

// ================================ inspect ================================

impl_sdk_bin! {
    InspectContext { current_height: u64, expected_chain_id: u32 } both
}

impl_sdk_bin! {
    HeightRangeDesc { start: u64, end: u64 } both
}

impl_sdk_bin! {
    Review {
        schema: str,
        codec_profile_hash: str,
        tx_type: u8,
        timestamp: u64,
        main: str,
        fee: str,
        gas_max: opt_u8,
        tx_hash: str,
        hash_with_fee: str,
        unsigned_body_hash: str,
        review_binding: str,
        signer_address: opt_str,
        inspect_context: opt_obj InspectContext,
        expired_height: opt_bool,
        wrong_chain: opt_bool,
        protocol_valid: bool,
        signability: str,
        auditability: str,
        requires_user_confirmation: bool,
        limits_violations: str_arr,
        required_signers: str_arr,
        present_signers: str_arr,
        missing_signers: str_arr,
        chain_ids_allowed: opt_u32_arr,
        valid_height_range: opt_obj HeightRangeDesc,
        fee_purity: opt_u64,
        fee_purity_ok: opt_bool,
        actions: obj_arr ActionDesc,
        asset_serials: u64_arr,
    } both
}

impl_sdk_bin! {
    SignatureEntry { public_key: str, signature: str } both
}

impl_sdk_bin! {
    TransactionJson {
        schema: str,
        tx_type: u8,
        timestamp: u64,
        main: str,
        fee: str,
        gas_max: opt_u8,
        tx_hash: str,
        hash_with_fee: str,
        unsigned_body_hash: str,
        actions: obj_arr ActionDesc,
        signatures: obj_arr SignatureEntry,
    } both
}

// ================================ attach ================================

impl_sdk_bin! {
    SigningRequest {
        schema: str,
        id: str,
        purpose: str,
        algorithm: str,
        signer_address: str,
        digest: str,
        body_hash: opt_str,
        review_binding: opt_str,
        policy_decision: opt_obj PolicyDecision,
        origin: opt_str,
        expires_at: opt_u64,
        request_binding: str,
    } both
}

impl_sdk_bin! {
    SignatureProof {
        schema: str,
        request_id: str,
        request_binding: str,
        public_key: str,
        signature: str,
        algorithm: str,
    } both
}

impl_sdk_bin! {
    AttachResult { schema: str, body: str, complete: bool, missing_signers: str_arr } to
}

impl_sdk_bin! {
    VerifyResult { schema: str, ok: bool, errors: str_arr } to
}

impl_sdk_bin! {
    SignatureReport {
        schema: str,
        required: str_arr,
        present: str_arr,
        valid: str_arr,
        missing: str_arr,
        invalid: str_arr,
    } to
}

// ================================ build ================================

impl_sdk_bin! {
    BuiltTransaction {
        schema: str,
        tx_type: u8,
        timestamp: u64,
        main: str,
        fee: str,
        hash: str,
        hash_with_fee: str,
        unsigned_body_hash: str,
        body: str,
    } to
}

// ================================ policy ================================

impl_sdk_bin! {
    Policy {
        schema: opt_str,
        deny_kinds: opt_u16_arr,
        deny_blob: opt_bool,
        max_diamond_names: opt_u32,
        confirm_auditability: opt_str_arr,
    } both
}

impl_sdk_bin! {
    PolicyDecision {
        schema: str,
        policy_id: str,
        policy_hash: str,
        review_binding: str,
        decision: str,
        findings: str_arr,
        policy_binding: str,
    } both
}

// ================================ message ================================

impl_sdk_bin! {
    MessagePrepareParams { digest: str, signer_address: str, origin: opt_str, expires_at: opt_u64 } from
}

// ================================ nested helpers ================================

/// Re-serialize a parsed object value back into a body so the typed
/// `from_binary` can parse it. Small cost, keeps the reader API simple.
fn reserialize_obj(value: &BVal) -> Ret<Vec<u8>> {
    reserialize_fields(value.obj()?)
}

fn reserialize_fields<'a>(fields: Vec<(&'a str, BVal<'a>)>) -> Ret<Vec<u8>> {
    let mut w = Bw::new();
    for (name, value) in fields {
        w.push_raw(name, &value);
    }
    Ok(w.into_inner())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Every nested layout reference (obj/opt_obj/obj_arr/opt_obj_arr) must
    /// resolve to a BIN_TYPES entry — the codegen renders the JS encoder/
    /// decoder from the same names, so an unresolved reference would fail
    /// the generated facade, not silently drop a field.
    #[test]
    fn bin_layout_nested_references_resolve() {
        fn walk(fields: &'static [BinField], out: &mut Vec<&'static str>) {
            for field in fields {
                match field.kind {
                    BinKind::Obj(n)
                    | BinKind::OptObj(n)
                    | BinKind::ObjArr(n)
                    | BinKind::OptObjArr(n) => out.push(n),
                    _ => {}
                }
            }
        }
        let mut names = Vec::new();
        for ty in BIN_TYPES {
            walk(ty.fields, &mut names);
        }
        for name in names {
            assert!(
                BIN_TYPES.iter().any(|t| t.js == name),
                "layout reference {name:?} has no BIN_TYPES entry"
            );
        }
    }

    /// The hand-declared `PayloadDesc` layout (the only non-macro layout)
    /// must match what the hand-written writer emits for every variant.
    #[test]
    fn payload_desc_layout_matches_writer() {
        let cases: Vec<(PayloadDesc, &[(&str, char)])> = vec![
            (
                PayloadDesc::Hac { amount: "1".to_owned() },
                &[("type", 's'), ("amount", 's')],
            ),
            (
                PayloadDesc::Satoshi { atoms: "2".to_owned() },
                &[("type", 's'), ("atoms", 's')],
            ),
            (
                PayloadDesc::Hacd {
                    count: 3,
                    names: vec!["AAABBB".to_owned()],
                },
                &[("type", 's'), ("count", 'i'), ("names", 'a')],
            ),
            (
                PayloadDesc::Asset {
                    serial: "4".to_owned(),
                    atoms: "5".to_owned(),
                },
                &[("type", 's'), ("serial", 's'), ("atoms", 's')],
            ),
        ];
        let tag_of = |value: &BVal| match value {
            BVal::Str(_) => 's',
            BVal::U64(_) => 'u',
            BVal::U32(_) => 'i',
            BVal::U8(_) => 't',
            BVal::Bool(_) => 'b',
            BVal::StrArr(_) => 'a',
            BVal::U64Arr(_) => 'A',
            BVal::U32Arr(_) => 'B',
            BVal::Obj(_) => 'o',
            BVal::ObjArr(_) => 'O',
            BVal::Null => 'n',
        };
        for (payload, expected) in cases {
            let body = payload.to_binary_body();
            let fields = parse(&body).unwrap();
            assert_eq!(fields.len(), expected.len(), "field count for {payload:?}");
            for ((name, value), (exp_name, exp_tag)) in fields.iter().zip(expected) {
                assert_eq!(name, exp_name, "field name for {payload:?}");
                assert_eq!(tag_of(value), *exp_tag, "field tag for {name} in {payload:?}");
            }
        }
    }


    /// Binary round-trip of the macro-generated simple types (locks the field
    /// set so a future refactor cannot silently drop or rename a field).
    #[test]
    fn simple_types_binary_round_trip() {
        let verify = crate::account::VerifyAddressResult {
            ok: true,
            error: None,
            address: Some("1abc".to_owned()),
        };
        let body = verify.to_binary_body();
        let fields = crate::bjson::parse(&body).unwrap();
        assert!(crate::bjson::req(&fields, "ok").unwrap().bool().unwrap());
        assert_eq!(crate::bjson::req(&fields, "address").unwrap().str().unwrap(), "1abc");

        let ctx = InspectContext {
            current_height: 123_456,
            expected_chain_id: 2,
        };
        let decoded = InspectContext::from_binary(&ctx.to_binary_body()).unwrap();
        assert_eq!(decoded, ctx);

        let built = crate::build::BuiltTransaction {
            schema: "s".to_owned(),
            tx_type: 2,
            timestamp: 3,
            main: "m".to_owned(),
            fee: "f".to_owned(),
            hash: "h".to_owned(),
            hash_with_fee: "hf".to_owned(),
            unsigned_body_hash: "ub".to_owned(),
            body: "b".to_owned(),
        };
        let body = built.to_binary_body();
        let fields = crate::bjson::parse(&body).unwrap();
        assert_eq!(crate::bjson::req(&fields, "tx_type").unwrap().u8().unwrap(), 2);
        assert_eq!(crate::bjson::req(&fields, "timestamp").unwrap().u64().unwrap(), 3);
        assert_eq!(crate::bjson::req(&fields, "main").unwrap().str().unwrap(), "m");

        let report = crate::attach::SignatureReport {
            schema: "s".to_owned(),
            required: vec!["a".to_owned()],
            present: vec![],
            valid: vec!["a".to_owned()],
            missing: vec![],
            invalid: vec![],
        };
        let body = report.to_binary_body();
        let fields = crate::bjson::parse(&body).unwrap();
        assert_eq!(
            crate::bjson::req(&fields, "required").unwrap().str_arr().unwrap(),
            vec!["a"]
        );
        assert_eq!(
            crate::bjson::req(&fields, "present").unwrap().str_arr().unwrap(),
            Vec::<&str>::new()
        );
    }

    #[test]
    fn request_objects_round_trip() {
        let ctx = InspectContext {
            current_height: 9,
            expected_chain_id: 1,
        };
        let decoded = InspectContext::from_binary(&ctx.to_binary_body()).unwrap();
        assert_eq!(decoded.current_height, 9);
        assert_eq!(decoded.expected_chain_id, 1);

        let proof = crate::attach::SignatureProof {
            schema: "s".to_owned(),
            request_id: "r".to_owned(),
            request_binding: "rb".to_owned(),
            public_key: "pk".to_owned(),
            signature: "sig".to_owned(),
            algorithm: "alg".to_owned(),
        };
        let decoded = crate::attach::SignatureProof::from_binary(&proof.to_binary_body()).unwrap();
        assert_eq!(decoded.request_id, "r");
        assert_eq!(decoded.public_key, "pk");

        let decision = crate::policy::PolicyDecision {
            schema: "s".to_owned(),
            policy_id: "p".to_owned(),
            policy_hash: "ph".to_owned(),
            review_binding: "rb".to_owned(),
            decision: "allow".to_owned(),
            findings: vec!["f1".to_owned()],
            policy_binding: "pb".to_owned(),
        };
        let decoded = crate::policy::PolicyDecision::from_binary(&decision.to_binary_body()).unwrap();
        assert_eq!(decoded.findings, vec!["f1".to_owned()]);

        let params = crate::message::MessagePrepareParams {
            digest: "d".to_owned(),
            signer_address: "sa".to_owned(),
            origin: Some("o".to_owned()),
            expires_at: Some(5),
        };
        let mut w = Bw::new();
        w.str("digest", "d");
        w.str("signer_address", "sa");
        w.str("origin", "o");
        w.u64("expires_at", 5);
        let decoded = crate::message::MessagePrepareParams::from_binary(&w.into_inner()).unwrap();
        assert_eq!(decoded, params);

        // Missing required field is rejected.
        assert!(InspectContext::from_binary(&[]).is_err());
    }
}
